sudo: required
dist: bionic
language: java
services:
- docker
jdk:
- openjdk11
env:
  global:
  - DOCKER_IMAGE=bcesnik/interface_image_rso:1.0.0-SNAPSHOT-$TRAVIS_JOB_NUMBER
  - secure: oqPCgpLFfTGd8UEhrW7xzN5n2NsH1xqT6+TM+ahJJ3v3ExfXfLCia40V5NYINTO4VdsDS2eYJ9tV3yQLfWxhy/DnmJ8RsxpZbJokgSe4qFlLcJdOHNg8XLy/4beMKPeMP4VwQofKYiuru4T1aWcG0F31ukso0Wm47NsjKle4P17AGQYmtOaa0sc1nXW2o1CQvsXD4GWxmT0Oq6vMa54qEi8dx1/GOdHZnrX9qxAXgO1P9k404XaMYuBQ1ZSowZjca5o2FkGFm6VZT6il4BptaNyCsKCC25TJUVs+34J8+AT29MEXYs+YToQn3+0rRMatuG1fQ89Bn7u5qkysFlJu+j0lGFgB/Zk93cFICSBdquHRHU4julalnq/BSyoxPXCbBmc4/UR4KqZLP4+IplmjPVVdgR3smK7os58Vl3thS5sfHd/PZ8yP63PS0aRj3kapPaDLK1mreuk9o0YkIDBvAVtQZ1d4hWn6k38I2zIqXVeL6fzoKeFZFb/suHXnkgRMdV21dFxhpe9IpU6Mxn33aU3HMZuntuqPTrleM2Q78tYmbozwA9pqPav2tACMjEoX2uhHkY36f8i8M2+ZUENMcdcOCNuU+RkKpMp6SWgASCCi5f72EnptyWAO8Nu0BsNdkR7n0liRXkHK//MOC2+W+fBSHnBRBV+gWqoNg0ZG0oE=
  - secure: tMhGLhNJTcd4rMG8z0m2sz1mWXQZigmkdqxkaZ1R+isg6elfL/pMWm2KXtAVis6UETnyVanRichAn7PdoTwtdN2kQSmWcn08pz75L7y+3C/2g8G/YJjobRwoHt9H0PjHqjMNK0dG/EyhxKJdT5qr4tM1TU+Xlm9N/uxetI3FIXe+tgXeMtTUcUGydxYA2DQ7wBfkQLFt/ltXnM2jgk/mukIK0mtbjcUaH/a7sM2tHRXas1gV8cym6fWKNB/bRz3wq+aL/1LPdMQwfdrT2Q6BJeWQ95cLQJ1hIClqzJ9U2YOQrOEDRaFXiCIAkVVNZHD3L9mfGhCEJhzg3lpVp9oPz5+F9z7oPKJV7JWH97dKRWrwWRaHxA6v0iRIGI0gakD3GPy0FMu82MpPGn3G8horpm02sxxw6tTv93w86S7zDV/D5A2YRyYFK2v9dENnUIM3GXYavGIPvMqFDHynDdYzZsJqjZWFmYU+MIFs8HzKN4jyKJo5mTNQRshVTvhNcWmfQI4ikbNqOlBtqOuJImnqRCvdd7fZIYY/KYSBPNq9HYavxQnRlz2PI/rP0NfMY27MUmLxyzieuFgJPG4yznIyHe5FhB4mUSWP8rCNk1OW/fBIbjUA20LuUwuUB7AwkXcI6aNbiQ8qqiEen1lYjHdqvjeEPsVaF8T79pqm9TFGqGg=
cache:
  directories:
  - "$HOME/.m2"
script:
- mvn clean package -U
- docker build -t "$DOCKER_IMAGE" .
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push "$DOCKER_IMAGE"
