apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-interface-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-interface
  template:
    metadata:
      labels:
        app: image-interface
    spec:
      containers:
      - image: bcesnik/interface_image_rso:1.0.0-SNAPSHOT-4.1
        name: image-interface
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: gcloud
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://image-interface-service:8084
        ports:
        - containerPort: 8084
          name: server
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: image-interface
spec:
  type: NodePort
  ports:
  - port: 8084
    protocol: TCP
    targetPort: 8084
  selector:
    app: image-comments
